### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by SusheelThapa** [qaidjoharj53/Blood-Bridge#11]
![image](https://github.com/qaidjoharj53/Blood-Bridge/assets/83917129/e686c320-37e5-46dd-8f33-887d99cbf4ad)

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @SusheelThapa  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 @rohitagr0310 , @jain-anshika .
