### ISSUE TITLE
Create a Contributing.md file

### ISSUE THREAD

**Issue by Akshith-S** [qaidjoharj53/Blood-Bridge#5]
It seems your project doesn't contain a contributing.md file. Having that file would be really helpful for beginners to know how to contribute to the project.

The repository requires general instructions about how people can contribute to this project.
General instruction:
How to set up the project.
How they can communicate through issues.
How to create pull requests etc (Make sure to create pulls to the master branch only)

**Comment by kclalit64** [comment]
kinda new to ocktoberfest..would be good way to start for me. Can you assign me this issue? @qaidjoharj53

**Comment by qaidjoharj53** [comment]
@Akshith-S @kclalit64 
This issue is being assigned to both of you.
PR will be merged on the basis of quality of work you did.
Just do this task and give your best 100%.

**Comment by qaidjoharj53** [comment]
@Akshith-S @kclalit64 
Since you both are not working on this issue, It may be assigned to someone else.
So complete this issue fast if you are interested.

**Comment by kclalit64** [comment]
sorry, was afk for last few days. will work on it

**Comment by jayesh2474** [comment]
Sorry @kclalit64 and @Akshith-S  but We Cant Wait More.

**Comment by kclalit64** [comment]
#Hi @jayesh2474 , you might have missed my PR for this issue  yesterday  #16 . am waiting for a follow up. Thanks!
